<?php
declare(strict_types=1);
require __DIR__ . '/../includes/bootstrap.php';
require_admin();
$counts = db()->query("SELECT (SELECT COUNT(*) FROM users) users, (SELECT COUNT(*) FROM events WHERE status='published') events, (SELECT COUNT(*) FROM bookings WHERE status IN ('pending','confirmed')) bookings, (SELECT COUNT(*) FROM enquiries WHERE status='new') enquiries")->fetch();
$events = db()->query("SELECT e.*, COALESCE(SUM(CASE WHEN b.status IN ('pending','confirmed') THEN b.quantity ELSE 0 END),0) booked, COUNT(b.id) booking_records FROM events e LEFT JOIN bookings b ON b.event_id=e.id GROUP BY e.id ORDER BY e.event_date DESC")->fetchAll();
$bookings = db()->query("SELECT b.*, u.name user_name, u.email, e.title event_title FROM bookings b JOIN users u ON u.id=b.user_id JOIN events e ON e.id=b.event_id ORDER BY b.created_at DESC LIMIT 20")->fetchAll();
$enquiries = db()->query("SELECT id,name,email,subject,status,created_at FROM enquiries ORDER BY created_at DESC LIMIT 20")->fetchAll();
$pageTitle = 'Administration dashboard';
$metaDescription = 'Secure EpicEvents administration area.';
$robots = 'noindex, nofollow';
require __DIR__ . '/../includes/header.php';
?>
<main id="main-content" class="page-shell admin-shell">
    <header class="dashboard-head"><div><p class="eyebrow">Administration</p><h1>Event operations</h1><p>Manage published events, reservations and customer enquiries.</p></div><a class="button button-primary" href="<?= e(url('admin/event_form.php')) ?>">Add event</a></header>
    <section class="stat-grid" aria-label="System summary"><article><span>Members</span><strong><?= (int)$counts['users'] ?></strong></article><article><span>Published events</span><strong><?= (int)$counts['events'] ?></strong></article><article><span>Active bookings</span><strong><?= (int)$counts['bookings'] ?></strong></article><article><span>New enquiries</span><strong><?= (int)$counts['enquiries'] ?></strong></article></section>
    <section class="admin-section" aria-labelledby="events-title"><div class="section-heading"><h2 id="events-title">Events</h2><a class="text-link" href="<?= e(url('admin/event_form.php')) ?>">Create event</a></div><div class="table-wrap"><table><thead><tr><th scope="col">Event</th><th scope="col">Date</th><th scope="col">Capacity</th><th scope="col">Status</th><th scope="col">Actions</th></tr></thead><tbody><?php foreach($events as $event): ?><tr><th scope="row"><strong><?= e($event['title']) ?></strong><span><?= e($event['category']) ?> · <?= e($event['location']) ?></span></th><td><?= e(date('j M Y',strtotime($event['event_date']))) ?></td><td><?= (int)$event['booked'] ?> / <?= (int)$event['capacity'] ?></td><td><span class="status status-<?= e($event['status']) ?>"><?= e(ucfirst($event['status'])) ?></span></td><td><div class="action-row"><a class="text-link" href="<?= e(url('admin/event_form.php?id='.$event['id'])) ?>">Edit</a><?php if($event['status']!=='archived'): ?><form method="post" action="<?= e(url('admin/event_archive.php')) ?>" class="inline-form"><?= csrf_field() ?><input type="hidden" name="id" value="<?= (int)$event['id'] ?>"><button class="text-button danger" type="submit" data-confirm="Archive this event? Existing booking records will remain.">Archive</button></form><?php endif; ?><?php if($event['status']!=='published' && (int)$event['booking_records']===0): ?><form method="post" action="<?= e(url('admin/event_delete.php')) ?>" class="inline-form"><?= csrf_field() ?><input type="hidden" name="id" value="<?= (int)$event['id'] ?>"><button class="text-button danger" type="submit" data-confirm="Permanently delete this event? This cannot be undone.">Delete</button></form><?php endif; ?></div></td></tr><?php endforeach; ?></tbody></table></div></section>
    <section class="admin-section" aria-labelledby="reservations-title"><h2 id="reservations-title">Recent reservations</h2><div class="table-wrap"><table><thead><tr><th scope="col">Guest</th><th scope="col">Event</th><th scope="col">Reference</th><th scope="col">Tickets</th><th scope="col">Status</th><th scope="col">Update</th></tr></thead><tbody><?php foreach($bookings as $booking): ?><tr><th scope="row"><strong><?= e($booking['user_name']) ?></strong><span><?= e($booking['email']) ?></span></th><td><?= e($booking['event_title']) ?></td><td><code><?= e($booking['booking_reference']) ?></code></td><td><?= (int)$booking['quantity'] ?></td><td><span class="status status-<?= e($booking['status']) ?>"><?= e(ucfirst($booking['status'])) ?></span></td><td><form class="action-row" method="post" action="<?= e(url('admin/booking_status.php')) ?>"><?= csrf_field() ?><input type="hidden" name="id" value="<?= (int)$booking['id'] ?>"><label class="sr-only" for="booking-status-<?= (int)$booking['id'] ?>">Status for <?= e($booking['booking_reference']) ?></label><select id="booking-status-<?= (int)$booking['id'] ?>" name="status"><option value="pending" <?= $booking['status']==='pending'?'selected':'' ?>>Pending</option><option value="confirmed" <?= $booking['status']==='confirmed'?'selected':'' ?>>Confirmed</option><option value="cancelled" <?= $booking['status']==='cancelled'?'selected':'' ?>>Cancelled</option></select><button class="button button-small" type="submit">Save</button></form></td></tr><?php endforeach; ?></tbody></table></div></section>
    <section class="admin-section" aria-labelledby="enquiries-title"><h2 id="enquiries-title">Recent enquiries</h2><div class="table-wrap"><table><thead><tr><th scope="col">Sender</th><th scope="col">Subject</th><th scope="col">Received</th><th scope="col">Status</th><th scope="col">Update</th></tr></thead><tbody><?php foreach($enquiries as $enquiry): ?><tr><th scope="row"><strong><?= e($enquiry['name']) ?></strong><span><?= e($enquiry['email']) ?></span></th><td><?= e($enquiry['subject']) ?></td><td><?= e(date('j M Y',strtotime($enquiry['created_at']))) ?></td><td><?= e(ucfirst($enquiry['status'])) ?></td><td><form class="action-row" method="post" action="<?= e(url('admin/enquiry_status.php')) ?>"><?= csrf_field() ?><input type="hidden" name="id" value="<?= (int)$enquiry['id'] ?>"><label class="sr-only" for="enquiry-status-<?= (int)$enquiry['id'] ?>">Enquiry status</label><select id="enquiry-status-<?= (int)$enquiry['id'] ?>" name="status"><option value="new" <?= $enquiry['status']==='new'?'selected':'' ?>>New</option><option value="in_progress" <?= $enquiry['status']==='in_progress'?'selected':'' ?>>In progress</option><option value="resolved" <?= $enquiry['status']==='resolved'?'selected':'' ?>>Resolved</option></select><button class="button button-small" type="submit">Save</button></form></td></tr><?php endforeach; ?></tbody></table></div></section>
</main>
<?php require __DIR__ . '/../includes/footer.php'; ?>
